### ISSUE TITLE
feature : get image from internet

### ISSUE THREAD

**Issue by bistcuite** [f-stop-lang/f-stop#2]
Example : 
```
OPEN_HTTP "https://example.com/myimg.png" AS image
...
```

**Comment by jay3332** [comment]
i think what you want is
 ```prolog
OPEN URL '...' AS image
```

**Comment by bistcuite** [comment]
> 
> 
> i think what you want is
> 
> ```prolog
> OPEN URL '...' AS image
> ```

It's better

**Comment by Tom-the-Bomb** [comment]
this is still in development, so you shouldnt really use it in production or w/e but feel free to test if you want
https://github.com/f-stop-lang/f-stop-rply/blob/master/fstop/parser.py#L217

**Comment by MrKomodoDragon** [comment]
i will add this right now.

**Comment by MrKomodoDragon** [comment]
Support has been added in commit 05833f5
